# Generated by Django 4.1.1 on 2022-09-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['create_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='c_time',
            new_name='create_time',
        ),
    ]
